# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\S11De\Desktop\SqrtPythonProject\UiCode\formBaseUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(610, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(230000, 230000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setToolTip("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 361, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.horizontalLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.leftBaseLayout = QtWidgets.QVBoxLayout()
        self.leftBaseLayout.setObjectName("leftBaseLayout")
        self.askLayout = QtWidgets.QVBoxLayout()
        self.askLayout.setObjectName("askLayout")
        self.askTextLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.askTextLabel.setObjectName("askTextLabel")
        self.askLayout.addWidget(self.askTextLabel)
        self.askTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.askTextBrowser.setReadOnly(False)
        self.askTextBrowser.setObjectName("askTextBrowser")
        self.askLayout.addWidget(self.askTextBrowser)
        self.leftBaseLayout.addLayout(self.askLayout)
        self.answerLayout = QtWidgets.QVBoxLayout()
        self.answerLayout.setObjectName("answerLayout")
        self.answerTextLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.answerTextLabel.setObjectName("answerTextLabel")
        self.answerLayout.addWidget(self.answerTextLabel)
        self.answerTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.answerTextBrowser.setDocumentTitle("")
        self.answerTextBrowser.setPlaceholderText("")
        self.answerTextBrowser.setObjectName("answerTextBrowser")
        self.answerLayout.addWidget(self.answerTextBrowser)
        self.leftBaseLayout.addLayout(self.answerLayout)
        self.answerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.answerButton.setObjectName("answerButton")
        self.leftBaseLayout.addWidget(self.answerButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.leftBaseLayout)
        self.rightBaseLayout = QtWidgets.QVBoxLayout()
        self.rightBaseLayout.setObjectName("rightBaseLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightBaseLayout.addItem(spacerItem)
        self.roundLayout = QtWidgets.QVBoxLayout()
        self.roundLayout.setObjectName("roundLayout")
        self.roundLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.roundLabel.setObjectName("roundLabel")
        self.roundLayout.addWidget(self.roundLabel)
        self.roundSpinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.roundSpinBox_2.setMinimum(1)
        self.roundSpinBox_2.setMaximum(20)
        self.roundSpinBox_2.setObjectName("roundSpinBox_2")
        self.roundLayout.addWidget(self.roundSpinBox_2)
        self.rightBaseLayout.addLayout(self.roundLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.rightBaseLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 610, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuLanguage = QtWidgets.QMenu(self.menuBar)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRussian = QtWidgets.QAction(MainWindow)
        self.actionRussian.setCheckable(True)
        self.actionRussian.setObjectName("actionRussian")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionDeutch = QtWidgets.QAction(MainWindow)
        self.actionDeutch.setCheckable(True)
        self.actionDeutch.setObjectName("actionDeutch")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuLanguage.addAction(self.actionRussian)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionDeutch)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionInfo)
        self.menuBar.addAction(self.menuLanguage.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sqrt"))
        self.askTextLabel.setText(_translate("MainWindow", "Поле для ввода"))
        self.answerTextLabel.setText(_translate("MainWindow", "Поле для ответа"))
        self.answerButton.setText(_translate("MainWindow", "Нажать, чтоб посчитать корни"))
        self.roundLabel.setText(_translate("MainWindow", "Округление"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Язык"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.actionRussian.setText(_translate("MainWindow", "Русский"))
        self.actionEnglish.setText(_translate("MainWindow", "Английский"))
        self.actionDeutch.setText(_translate("MainWindow", "Немецкий"))
        self.actionHelp.setText(_translate("MainWindow", "Форум"))
        self.actionInfo.setText(_translate("MainWindow", "Информация"))

