# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\S11De\Desktop\SqrtPythonProject\UiCode\formBaseUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(610, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(230000, 230000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setToolTip("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 361, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.horizontalLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.leftBaseLayout = QtWidgets.QVBoxLayout()
        self.leftBaseLayout.setObjectName("leftBaseLayout")
        self.askLayout = QtWidgets.QVBoxLayout()
        self.askLayout.setObjectName("askLayout")
        self.askTextLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.askTextLabel.setObjectName("askTextLabel")
        self.askLayout.addWidget(self.askTextLabel)
        self.askTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.askTextBrowser.setReadOnly(False)
        self.askTextBrowser.setObjectName("askTextBrowser")
        self.askLayout.addWidget(self.askTextBrowser)
        self.leftBaseLayout.addLayout(self.askLayout)
        self.answerLayout = QtWidgets.QVBoxLayout()
        self.answerLayout.setObjectName("answerLayout")
        self.answerTextLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.answerTextLabel.setObjectName("answerTextLabel")
        self.answerLayout.addWidget(self.answerTextLabel)
        self.answerTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.answerTextBrowser.setDocumentTitle("")
        self.answerTextBrowser.setPlaceholderText("")
        self.answerTextBrowser.setObjectName("answerTextBrowser")
        self.answerLayout.addWidget(self.answerTextBrowser)
        self.leftBaseLayout.addLayout(self.answerLayout)
        self.answerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.answerButton.setObjectName("answerButton")
        self.leftBaseLayout.addWidget(self.answerButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.leftBaseLayout)
        self.rightBaseLayout = QtWidgets.QVBoxLayout()
        self.rightBaseLayout.setObjectName("rightBaseLayout")
        self.helpLayout = QtWidgets.QVBoxLayout()
        self.helpLayout.setObjectName("helpLayout")
        self.helpLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.helpLabel.setObjectName("helpLabel")
        self.helpLayout.addWidget(self.helpLabel)
        self.helpComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.helpComboBox.setObjectName("helpComboBox")
        self.helpLayout.addWidget(self.helpComboBox)
        self.rightBaseLayout.addLayout(self.helpLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightBaseLayout.addItem(spacerItem)
        self.roundLayout = QtWidgets.QVBoxLayout()
        self.roundLayout.setObjectName("roundLayout")
        self.roundLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.roundLabel.setObjectName("roundLabel")
        self.roundLayout.addWidget(self.roundLabel)
        self.roundSpinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.roundSpinBox_2.setMinimum(1)
        self.roundSpinBox_2.setMaximum(20)
        self.roundSpinBox_2.setObjectName("roundSpinBox_2")
        self.roundLayout.addWidget(self.roundSpinBox_2)
        self.rightBaseLayout.addLayout(self.roundLayout)
        self.languageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.languageLabel.setObjectName("languageLabel")
        self.rightBaseLayout.addWidget(self.languageLabel)
        self.languageComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.languageComboBox.setObjectName("languageComboBox")
        self.rightBaseLayout.addWidget(self.languageComboBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.rightBaseLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sqrt"))
        self.askTextLabel.setText(_translate("MainWindow", "Поле для ввода"))
        self.answerTextLabel.setText(_translate("MainWindow", "Поле для ответа"))
        self.answerButton.setText(_translate("MainWindow", "Push to take sqr"))
        self.helpLabel.setText(_translate("MainWindow", "Помощь"))
        self.roundLabel.setText(_translate("MainWindow", "Округление"))
        self.languageLabel.setText(_translate("MainWindow", "Язык"))

